spring:
  application:
    name: order-service
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
      database: 0
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/